### ISSUE TITLE
Segmentation fault (core dumped) at go get github.com/eBay/fabio

### ISSUE THREAD

**Issue by kklepper** [strarsis/consul-fabio-example#1] opened 2016-04-09 19:25 UTC
Everything went fine until 

```
$ go get github.com/eBay/fabio
Segmentation fault (core dumped)
```

What now? I'm on AWS EC2 Ubuntu t2.micro.

**Comment by strarsis** [comment] 2016-04-09 22:03
This seems to be an issue with your go installation:
https://github.com/go-gomail/gomail/issues/11

Go version manager:
https://github.com/moovweb/gvm

Or you may try the docker images for go:
https://github.com/moovweb/gvm

With best regards

**Comment by kklepper** [comment] 2016-04-09 22:36
Thank you very much.

```
$ go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

$ gvm list

gvm gos (installed)

   system
```

I'm confused. Any help? 

This is what I did before:

```
$ go build server.go
The program 'go' is currently not installed. You can install it by typing:
sudo apt-get install gccgo-go



$ sudo apt-get install gccgo-go
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  gccgo gccgo-4.9 libgo5
Suggested packages:
  gccgo-multilib gccgo-4.9-doc libgo5-dbg
The following NEW packages will be installed:
  gccgo gccgo-4.9 gccgo-go libgo5
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 24.5 MB of archives.
After this operation, 110 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libgo5 amd64 4.9.3-0ubuntu4 [2,600 kB]
Get:2 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/universe gccgo-4.9 amd64 4.9.3-0ubuntu4 [21.5 MB]
Get:3 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu/ trusty/universe gccgo amd64 4:4.9-1ubuntu6 [1,060 B]
Get:4 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/universe gccgo-go amd64 1.2.1-0ubuntu1.2 [424 kB]
Fetched 24.5 MB in 1s (18.4 MB/s)
Selecting previously unselected package libgo5:amd64.
(Reading database ... 151538 files and directories currently installed.)
Preparing to unpack .../libgo5_4.9.3-0ubuntu4_amd64.deb ...
Unpacking libgo5:amd64 (4.9.3-0ubuntu4) ...
Selecting previously unselected package gccgo-4.9.
Preparing to unpack .../gccgo-4.9_4.9.3-0ubuntu4_amd64.deb ...
Unpacking gccgo-4.9 (4.9.3-0ubuntu4) ...
Selecting previously unselected package gccgo.
Preparing to unpack .../gccgo_4%3a4.9-1ubuntu6_amd64.deb ...
Unpacking gccgo (4:4.9-1ubuntu6) ...
Selecting previously unselected package gccgo-go.
Preparing to unpack .../gccgo-go_1.2.1-0ubuntu1.2_amd64.deb ...
Unpacking gccgo-go (1.2.1-0ubuntu1.2) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up libgo5:amd64 (4.9.3-0ubuntu4) ...
Setting up gccgo-4.9 (4.9.3-0ubuntu4) ...
Setting up gccgo (4:4.9-1ubuntu6) ...
Setting up gccgo-go (1.2.1-0ubuntu1.2) ...
update-alternatives: using /usr/bin/gccgo-go to provide /usr/bin/go (go) in auto mode
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
```

**Comment by strarsis** [comment] 2016-04-09 22:56
Try this (https://github.com/moovweb/gvm#a-note-on-compiling-go-15 for 1.6):

```
gvm install go1.4 -B
gvm use go1.4
export GOROOT_BOOTSTRAP=$GOROOT
gvm install go1.6
gvm use go1.6
```

Then run the go get command again and check whether it works now.

With best regards

**Comment by kklepper** [comment] 2016-04-09 23:10
Thanks a lot!

```
$ gvm install go1.6
Downloading Go source...
Installing go1.6...
 * Compiling...
ERROR: Failed to compile. Check the logs at /home/ubuntu/.gvm/logs/go-go1.6-compile.log
ERROR: Failed to use installed version

$ cat /home/ubuntu/.gvm/logs/go-go1.6-compile.log 
##### Building Go bootstrap tool.
cmd/dist
ERROR: Cannot find /home/ubuntu/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
```

Funny and strange. 1.6 needs 1.4 to compile? I'm used to `apt-get install`  and things work.

**Comment by strarsis** [comment] 2016-04-09 23:19
Right, Go 1.5+ requires older Go for bootstrapping.
I edited my answer and added some commands, you probably tried it before the edit.

**Comment by strarsis** [comment] 2016-04-10 00:06
So, does it work now with latest stable Go (1.6) 
instead with the system go provided by the distribution package?

**Comment by kklepper** [comment] 2016-04-10 08:24
Thank you very much again. Still something wrong.

```
ubuntu@ip-172-31-30-16:~/fabio/consul-fabio-example$ gvm install go1.4 -B
Installing go1.4 from binary source
ubuntu@ip-172-31-30-16:~/fabio/consul-fabio-example$
ubuntu@ip-172-31-30-16:~/fabio/consul-fabio-example$ gvm use go1.4
Now using version go1.4
ubuntu@ip-172-31-30-16:~/fabio/consul-fabio-example$
ubuntu@ip-172-31-30-16:~/fabio/consul-fabio-example$ export GOROOT_BOOTSTRAP=$GOROOT
ubuntu@ip-172-31-30-16:~/fabio/consul-fabio-example$
ubuntu@ip-172-31-30-16:~/fabio/consul-fabio-example$ gvm install go1.6
Installing go1.6...
 * Compiling...
ERROR: Failed to compile. Check the logs at /home/ubuntu/.gvm/logs/go-go1.6-compile.log
ERROR: Failed to use installed version
ubuntu@ip-172-31-30-16:~/fabio/consul-fabio-example$ cat /home/ubuntu/.gvm/logs/go-go1.6-compile.log
##### Building Go bootstrap tool.
cmd/dist

##### Building Go toolchain using /home/ubuntu/.gvm/gos/go1.4.
bootstrap/internal/obj
go build bootstrap/internal/obj: /home/ubuntu/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: fork/exec /home/ubuntu/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: cannot allocate memory
bootstrap/asm/internal/flags
go build bootstrap/asm/internal/flags: /home/ubuntu/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: fork/exec /home/ubuntu/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: cannot allocate memory
bootstrap/compile/internal/big
go build bootstrap/compile/internal/big: /home/ubuntu/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: fork/exec /home/ubuntu/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: cannot allocate memory
bootstrap/internal/gcprog
go build bootstrap/internal/gcprog: /home/ubuntu/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: fork/exec /home/ubuntu/.gvm/gos/go1.4/pkg/tool/linux_amd64/6g: cannot allocate memory
go tool dist: FAILED: /home/ubuntu/.gvm/gos/go1.4/bin/go install -v bootstrap/...: exit status 1
```

**Comment by strarsis** [comment] 2016-04-10 13:05
You probably ran out of memory. Go is also built (much) faster with plenty of memory.
When this runs inside a VM, it should be easy to increase its available RAM.

**Comment by kklepper** [comment] 2016-04-10 18:27
Well, I'm on the free tier now, getting my feet wet, so increasing RAM isn't that pleasant an option.

```
ubuntu@ip-172-31-30-16:~$ export GOROOT_BOOTSTRAP=$GOROOT
ubuntu@ip-172-31-30-16:~$  gvm install go1.6
Installing go1.6...
 * Compiling...
ERROR: Failed to compile. Check the logs at /home/ubuntu/.gvm/logs/go-go1.6-compile.log
ERROR: Failed to use installed version
ubuntu@ip-172-31-30-16:~$ free -m
             total       used       free     shared    buffers     cached
Mem:           992        286        706          2         25        151
-/+ buffers/cache:        109        883
Swap:         1023          0       1023
```

**Comment by strarsis** [comment] 2016-04-10 18:29
Prebuilt Go: https://www.digitalocean.com/community/tutorials/how-to-install-go-1-6-on-ubuntu-14-04

**Comment by kklepper** [comment] 2016-04-10 18:42
Thanks a lot! Will do as soon as possible.

**Comment by kklepper** [comment] 2016-04-11 09:51
Ok. Went fine. Now proceed:

```
ubuntu@ip-172-31-30-16:~/fabio$ go get github.com/eBay/fabio
# github.com/eBay/fabio/route
src/github.com/eBay/fabio/route/table.go:22:11: error: reference to undefined identifier ‘atomic.Value’
 var table atomic.Value
           ^
# github.com/hashicorp/go-cleanhttp
src/github.com/hashicorp/go-cleanhttp/cleanhttp.go:27:4: error: unknown field ‘KeepAlive’ in ‘net.Dialer’
    KeepAlive: 30 * time.Second,
    ^
src/github.com/hashicorp/go-cleanhttp/cleanhttp.go:29:3: error: unknown field ‘TLSHandshakeTimeout’ in ‘http.Transport’
   TLSHandshakeTimeout: 10 * time.Second,
```

**Comment by strarsis** [comment] 2016-04-11 10:08
This is probably caused by some package dependencies of your go installation, e.g. 
https://github.com/hashicorp/go-cleanhttp/issues/5 .
The wrong variant of gccgo may be used, check the already installed go-related packages.

Also either uninstall gvm (go version manager) or switch to the newly installed go, using it, if possible - ideally you would just start over with the cloud instance.

**Comment by kklepper** [comment] 2016-04-11 10:24
I followed http://stackoverflow.com/questions/14878271/how-to-uninstall-gvm, to no avail.

```
ubuntu@ip-172-31-30-16:~/fabio$ echo $PATH
/home/ubuntu/.gvm/bin:/home/ubuntu/.gvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
```

Cleaned to 

```
ubuntu@ip-172-31-30-16:~/fabio$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
```

No change.

Don't know what to learn from  https://github.com/hashicorp/go-cleanhttp/issues/5.

**Comment by strarsis** [comment] 2016-04-16 14:04
I am very busy at the moment, hence the delayed answer.

Would it be possible for you starting from scratch with this instance?
Installing Go again cleanly using the mentioned tutorial (https://www.digitalocean.com/community/tutorials/how-to-install-go-1-6-on-ubuntu-14-04) 
without installing any Go related packages from Ubuntu official repository 
should result in a working and recent enough Go installation.

With best regards

**Comment by kklepper** [comment] 2016-04-17 18:02
Thank you very much, will do, but am busy right now as well. I'll come back to you soon.

**Comment by strarsis** [comment] 2016-06-29 23:22
Have you been able to run it?
I closed this issue, if you have any questions, re-open it.

**Closed as completed by strarsis** 2016-06-29 23:22 UTC
